### PR TITLE
added square thumbs , thumbs padding patch

### PR DESCRIPTION
**Pull request by siduck76**
Hi there! I added [square_thumbs](https://github.com/explosion-mental/sxiv/blob/main/patches/square-thumbs.patch) and [thumbs_padding](https://github.com/explosion-mental/sxiv/blob/main/patches/thumb_paddings.patch) patch. 

before : 

2021-06-06-072735_1366x768_scrot

after : 

image

### CODE REVIEW

**Comment by bakkeby** [comment]
The square thumbs patch is already there. I can look into adding the thumbs padding patch, but not hardcoded like this.

Also for some reason you include thumbs.c.rej and thumbs.c.orig in the pull request?

**Comment by siduck76** [comment]
oh sorry , I forgot to remove them. I removed them now.

**Comment by bakkeby** [comment]
I added the thumb paddings patch so I'll close this one.

**Comment by siduck76** [comment]
> The square thumbs patch is already there. I can look into adding the thumbs padding patch, but not hardcoded like this.
> 
> Also for some reason you include thumbs.c.rej and thumbs.c.orig in the pull request?

I tried the build and the square thumbs doesnt seem to work 

image

config.h 

image

**Comment by bakkeby** [comment]
Did you enable `SQUARE_THUMBNAILS_PATCH` in [patches.h](https://github.com/bakkeby/sxiv-flexipatch/blob/master/patches.def.h#L49-L52)?

**Comment by siduck76** [comment]
oh I didnt know we had to do that , thx!

**Comment by siduck76** [comment]
@bakkeby I do have librsvg and librsvg-devel , cairo-devel but sxiv sitll doesnt compile 

image

**Comment by siduck76** [comment]
@bakkeby I did uncomment them and now I get this url.h error 

image

**Comment by bakkeby** [comment]
There is a line underneath the one you uncommented called curlobjs, you need to uncomment that as well.

**Comment by siduck76** [comment]
> There is a line underneath the one you uncommented called curlobjs, you need to uncomment that as well.

done but still same error :( 

image

**Comment by explosion-mental** [comment]
> > The square thumbs patch is already there. I can look into adding the thumbs padding patch, but not hardcoded like this.
> > Also for some reason you include thumbs.c.rej and thumbs.c.orig in the pull request?
> 
> I tried the build and the square thumbs , zero padding doesnt seem to work
> 
> image
> 
> config.h
> 
> image
> 
> my build :
> 
> image

Try Margin = -4 and Borders = -2 I actually was veery interested in that same thing, I didn't like spaces around. You may need to play around with the thumb_sizes array ( I have '32, 64, 116, 145, 181, 286, 361, 412' and thumb_size on 3 ) and search for the perfect fit. I figure out it depends on you monitor and wether you have gaps or not on your window manager.

**Comment by bakkeby** [comment]
@siduck76 sorry that was a bit embarrassing, I forgot to actually add url.c / url.h to git 🤦🏻‍♂️ - should be fixed now.

**Comment by bakkeby** [comment]
@explosion-mental you say

> I tried the build and the square thumbs , zero padding doesnt seem to work

How do you mean?

If I have these settings:
```c
/* thumbnail sizes in pixels (width == height): */
static const int thumb_sizes[] = { 32, 64, 116, 145, 181, 286, 361, 412 };

const int THUMB_BORDERS[] = { 0, 0, 0, 0, 0, 0, 0, 0 };
const int THUMB_MARGIN = 0;
const int THUMB_PADDING = 0;

/* thumbnail size at startup, index into thumb_sizes[]: */
static const int THUMB_SIZE = 3;
```
then the thumbnails show up with no borders or gaps between them.

image

**Comment by explosion-mental** [comment]
@bakkeby yes, just mentioning that thumb_sizes is where you tweak if you get spaces between images and the actual window. This can change by the amount of space that sxiv window gets (whether you have a bar, gaps or is on fullscreen; i guess resolution as well). Also you may want to have THUMB_BORDERS at least to 1 since the selection rectangle will "overwrite" the image (barely noticeable).

**Comment by bakkeby** [comment]
@explosion-mental ah yes, that's has to do with how the border is drawn, more precisely when it hides the previous border (by simply writing it again using the background color). I noticed the same with the mark border patch - an unmarked thumbnail will always be cropped a tiny bit.

**Pull request closed without merging**
